import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { Web3Provider } from "@/components/Web3Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Web3Provider>
        {/* Sidebar + Main in one row */}
         <Navbar />
        <div className="flex min-h-screen gap-5">
          <Sidebar />
         

          <div className="flex-1  text-white overflow-y-auto">
            {children}
          </div>
        </div>

        {/* Footer independent at bottom */}
        <Footer />
        </Web3Provider>
      </body>
    </html>
  );
}
